version: '3.8'

services:
  nginx:
    image: doc1:v14 # Ваш локальный образ
    container_name: my-nginx-container
    ports:
      - "80:80"
      - "8080:8080" # Порт для статуса Nginx
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest # Официальный образ Nginx Exporter
    container_name: nginx-exporter
    ports:
      - "9113:9113" # Порт для метрик
    environment:
      - NGINX_SCRAPE_URI=http://nginx:8080/nginx_status
    depends_on:
      - nginx
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest # Официальный образ Prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # Порт для Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx-exporter
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest # Официальный образ Grafana
    container_name: grafana
    ports:
      - "3000:3000" # Порт для Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Имя администратора
      - GF_SECURITY_ADMIN_PASSWORD=admin # Пароль администратора
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge