version: '3.8'

services:
  nginx:
    image: doc1:v15 # Ваш локальный образ
    container_name: my-nginx-container
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.0.0 # Официальный образ Nginx Exporter
    container_name: nginx-exporter
    command:
      - --nginx.scrape-uri=http://nginx:8080/basic_status    
    ports:
      - "9113:9113" # Порт для метрик

  prometheus:
    image: prom/prometheus:latest # Официальный образ Prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # Порт для Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest # Официальный образ Grafana
    container_name: grafana
    ports:
      - "3000:3000" # Порт для Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Имя администратора
      - GF_SECURITY_ADMIN_PASSWORD=admin # Пароль администратора